// Generated by scripts/build-beats-data.mjs from public/images/manifest.json + voiceover.json. Do not hand-edit; rerun the script instead.
export interface BeatWord {
  text: string;
  keyword: boolean;
}
export interface BeatChunk {
  words: BeatWord[];
}
export interface Beat {
  id: string;
  asset: string;
  bgAsset?: string;
  fgAsset?: string;
  motion: "static" | "zoom-in" | "pan-lr" | "pan-du" | "fade-scale" | "slide-up";
  startFrame: number;
  durationFrames: number;
  text: string;
  chunks: BeatChunk[];
}

export const TOTAL_FRAMES = 4790;

export const beats: Beat[] = [
  {
    "id": "vo_01",
    "asset": "images/scene-vo_01.png",
    "motion": "static",
    "startFrame": 0,
    "durationFrames": 90,
    "text": "Kéo một đường ngang cắt nước Mỹ làm đôi.",
    "chunks": [
      {
        "words": [
          {
            "text": "Kéo",
            "keyword": false
          },
          {
            "text": "một",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "đường",
            "keyword": false
          },
          {
            "text": "ngang",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "cắt",
            "keyword": false
          },
          {
            "text": "nước",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "Mỹ",
            "keyword": false
          },
          {
            "text": "làm",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "đôi.",
            "keyword": false
          }
        ]
      }
    ]
  },
  {
    "id": "vo_02",
    "asset": "images/scene-vo_02.png",
    "motion": "zoom-in",
    "startFrame": 90,
    "durationFrames": 106,
    "text": "Nửa phía tây, Wyoming và Colorado",
    "chunks": [
      {
        "words": [
          {
            "text": "Nửa",
            "keyword": false
          },
          {
            "text": "phía",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "tây,",
            "keyword": false
          },
          {
            "text": "Wyoming",
            "keyword": true
          }
        ]
      },
      {
        "words": [
          {
            "text": "và",
            "keyword": false
          },
          {
            "text": "Colorado",
            "keyword": true
          }
        ]
      }
    ]
  },
  {
    "id": "vo_03",
    "asset": "images/scene-vo_03.png",
    "motion": "static",
    "startFrame": 196,
    "durationFrames": 96,
    "text": "là hai hình chữ nhật gần như hoàn hảo,",
    "chunks": [
      {
        "words": [
          {
            "text": "là",
            "keyword": false
          },
          {
            "text": "hai",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "hình",
            "keyword": false
          },
          {
            "text": "chữ",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "nhật",
            "keyword": false
          },
          {
            "text": "gần",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "như",
            "keyword": false
          },
          {
            "text": "hoàn",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "hảo,",
            "keyword": false
          }
        ]
      }
    ]
  },
  {
    "id": "vo_04",
    "asset": "images/scene-vo_04.png",
    "motion": "static",
    "startFrame": 292,
    "durationFrames": 86,
    "text": "cạnh thẳng tắp như được kẻ bằng thước.",
    "chunks": [
      {
        "words": [
          {
            "text": "cạnh",
            "keyword": false
          },
          {
            "text": "thẳng",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "tắp",
            "keyword": false
          },
          {
            "text": "như",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "được",
            "keyword": false
          },
          {
            "text": "kẻ",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "bằng",
            "keyword": false
          },
          {
            "text": "thước.",
            "keyword": false
          }
        ]
      }
    ]
  },
  {
    "id": "vo_05",
    "asset": "images/scene-vo_05.png",
    "motion": "pan-lr",
    "startFrame": 378,
    "durationFrames": 113,
    "text": "Nhưng chỉ cần bước qua sông Mississippi về phía đông,",
    "chunks": [
      {
        "words": [
          {
            "text": "Nhưng",
            "keyword": false
          },
          {
            "text": "chỉ",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "cần",
            "keyword": false
          },
          {
            "text": "bước",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "qua",
            "keyword": false
          },
          {
            "text": "sông",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "Mississippi",
            "keyword": true
          },
          {
            "text": "về",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "phía",
            "keyword": false
          },
          {
            "text": "đông,",
            "keyword": false
          }
        ]
      }
    ]
  },
  {
    "id": "vo_06",
    "asset": "images/scene-vo_06.png",
    "motion": "zoom-in",
    "startFrame": 491,
    "durationFrames": 99,
    "text": "ranh giới bang bỗng vặn vẹo, gãy khúc,",
    "chunks": [
      {
        "words": [
          {
            "text": "ranh",
            "keyword": false
          },
          {
            "text": "giới",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "bang",
            "keyword": false
          },
          {
            "text": "bỗng",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "vặn",
            "keyword": false
          },
          {
            "text": "vẹo,",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "gãy",
            "keyword": false
          },
          {
            "text": "khúc,",
            "keyword": false
          }
        ]
      }
    ]
  },
  {
    "id": "vo_07",
    "asset": "images/scene-vo_07.png",
    "motion": "pan-du",
    "startFrame": 590,
    "durationFrames": 104,
    "text": "có chỗ lượn theo một dòng sông suốt hàng trăm dặm.",
    "chunks": [
      {
        "words": [
          {
            "text": "có",
            "keyword": false
          },
          {
            "text": "chỗ",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "lượn",
            "keyword": false
          },
          {
            "text": "theo",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "một",
            "keyword": false
          },
          {
            "text": "dòng",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "sông",
            "keyword": false
          },
          {
            "text": "suốt",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "hàng",
            "keyword": false
          },
          {
            "text": "trăm",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "dặm.",
            "keyword": false
          }
        ]
      }
    ]
  },
  {
    "id": "vo_08",
    "asset": "images/scene-vo_08.png",
    "motion": "static",
    "startFrame": 694,
    "durationFrames": 96,
    "text": "Cùng một quốc gia, cùng một chính phủ,",
    "chunks": [
      {
        "words": [
          {
            "text": "Cùng",
            "keyword": false
          },
          {
            "text": "một",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "quốc",
            "keyword": false
          },
          {
            "text": "gia,",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "cùng",
            "keyword": false
          },
          {
            "text": "một",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "chính",
            "keyword": false
          },
          {
            "text": "phủ,",
            "keyword": false
          }
        ]
      }
    ]
  },
  {
    "id": "vo_09",
    "asset": "images/scene-vo_09.png",
    "motion": "fade-scale",
    "startFrame": 790,
    "durationFrames": 123,
    "text": "tại sao ranh giới lại được vẽ theo hai logic hoàn toàn trái ngược?",
    "chunks": [
      {
        "words": [
          {
            "text": "tại",
            "keyword": false
          },
          {
            "text": "sao",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "ranh",
            "keyword": false
          },
          {
            "text": "giới",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "lại",
            "keyword": false
          },
          {
            "text": "được",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "vẽ",
            "keyword": false
          },
          {
            "text": "theo",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "hai",
            "keyword": false
          },
          {
            "text": "logic",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "hoàn",
            "keyword": false
          },
          {
            "text": "toàn",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "trái",
            "keyword": false
          },
          {
            "text": "ngược?",
            "keyword": false
          }
        ]
      }
    ]
  },
  {
    "id": "vo_10",
    "asset": "images/scene-vo_10.png",
    "motion": "static",
    "startFrame": 913,
    "durationFrames": 102,
    "text": "Câu trả lời nằm ở khoảng cách gần hai trăm năm",
    "chunks": [
      {
        "words": [
          {
            "text": "Câu",
            "keyword": false
          },
          {
            "text": "trả",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "lời",
            "keyword": false
          },
          {
            "text": "nằm",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "ở",
            "keyword": false
          },
          {
            "text": "khoảng",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "cách",
            "keyword": false
          },
          {
            "text": "gần",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "hai",
            "keyword": false
          },
          {
            "text": "trăm",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "năm",
            "keyword": false
          }
        ]
      }
    ]
  },
  {
    "id": "vo_11",
    "asset": "images/scene-vo_11.png",
    "motion": "fade-scale",
    "startFrame": 1015,
    "durationFrames": 75,
    "text": "giữa hai cách vẽ bản đồ.",
    "chunks": [
      {
        "words": [
          {
            "text": "giữa",
            "keyword": false
          },
          {
            "text": "hai",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "cách",
            "keyword": false
          },
          {
            "text": "vẽ",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "bản",
            "keyword": false
          },
          {
            "text": "đồ.",
            "keyword": false
          }
        ]
      }
    ]
  },
  {
    "id": "vo_12",
    "asset": "images/scene-vo_12.png",
    "motion": "static",
    "startFrame": 1090,
    "durationFrames": 97,
    "text": "Mười ba thuộc địa đầu tiên của nước Mỹ",
    "chunks": [
      {
        "words": [
          {
            "text": "Mười",
            "keyword": false
          },
          {
            "text": "ba",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "thuộc",
            "keyword": false
          },
          {
            "text": "địa",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "đầu",
            "keyword": false
          },
          {
            "text": "tiên",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "của",
            "keyword": false
          },
          {
            "text": "nước",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "Mỹ",
            "keyword": false
          }
        ]
      }
    ]
  },
  {
    "id": "vo_13",
    "asset": "images/scene-vo_13.png",
    "motion": "slide-up",
    "startFrame": 1187,
    "durationFrames": 87,
    "text": "ra đời từ những đặc quyền hoàng gia",
    "chunks": [
      {
        "words": [
          {
            "text": "ra",
            "keyword": false
          },
          {
            "text": "đời",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "từ",
            "keyword": false
          },
          {
            "text": "những",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "đặc",
            "keyword": false
          },
          {
            "text": "quyền",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "hoàng",
            "keyword": false
          },
          {
            "text": "gia",
            "keyword": false
          }
        ]
      }
    ]
  },
  {
    "id": "vo_14",
    "asset": "images/scene-vo_14.png",
    "motion": "static",
    "startFrame": 1274,
    "durationFrames": 109,
    "text": "do vua Charles Đệ Nhị và những người kế vị",
    "chunks": [
      {
        "words": [
          {
            "text": "do",
            "keyword": false
          },
          {
            "text": "vua",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "Charles",
            "keyword": true
          },
          {
            "text": "Đệ",
            "keyword": true
          }
        ]
      },
      {
        "words": [
          {
            "text": "Nhị",
            "keyword": true
          },
          {
            "text": "và",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "những",
            "keyword": false
          },
          {
            "text": "người",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "kế",
            "keyword": false
          },
          {
            "text": "vị",
            "keyword": false
          }
        ]
      }
    ]
  },
  {
    "id": "vo_15",
    "asset": "images/scene-vo_15.png",
    "motion": "static",
    "startFrame": 1383,
    "durationFrames": 72,
    "text": "ký vào thế kỷ mười bảy.",
    "chunks": [
      {
        "words": [
          {
            "text": "ký",
            "keyword": false
          },
          {
            "text": "vào",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "thế",
            "keyword": false
          },
          {
            "text": "kỷ",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "mười",
            "keyword": false
          },
          {
            "text": "bảy.",
            "keyword": false
          }
        ]
      }
    ]
  },
  {
    "id": "vo_16",
    "asset": "images/scene-vo_16.png",
    "motion": "fade-scale",
    "startFrame": 1455,
    "durationFrames": 125,
    "text": "Khi đó, chưa có vệ tinh, chưa có định vị chính xác.",
    "chunks": [
      {
        "words": [
          {
            "text": "Khi",
            "keyword": false
          },
          {
            "text": "đó,",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "chưa",
            "keyword": false
          },
          {
            "text": "có",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "vệ",
            "keyword": false
          },
          {
            "text": "tinh,",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "chưa",
            "keyword": false
          },
          {
            "text": "có",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "định",
            "keyword": false
          },
          {
            "text": "vị",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "chính",
            "keyword": false
          },
          {
            "text": "xác.",
            "keyword": false
          }
        ]
      }
    ]
  },
  {
    "id": "vo_17",
    "asset": "images/scene-vo_17.png",
    "motion": "pan-lr",
    "startFrame": 1580,
    "durationFrames": 117,
    "text": "Người ta vẽ biên giới dựa trên những gì mắt thường nhìn thấy:",
    "chunks": [
      {
        "words": [
          {
            "text": "Người",
            "keyword": false
          },
          {
            "text": "ta",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "vẽ",
            "keyword": false
          },
          {
            "text": "biên",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "giới",
            "keyword": false
          },
          {
            "text": "dựa",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "trên",
            "keyword": false
          },
          {
            "text": "những",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "gì",
            "keyword": false
          },
          {
            "text": "mắt",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "thường",
            "keyword": false
          },
          {
            "text": "nhìn",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "thấy:",
            "keyword": false
          }
        ]
      }
    ]
  },
  {
    "id": "vo_18",
    "asset": "images/scene-vo_18.png",
    "motion": "static",
    "startFrame": 1697,
    "durationFrames": 89,
    "text": "một con sông, một dãy núi.",
    "chunks": [
      {
        "words": [
          {
            "text": "một",
            "keyword": false
          },
          {
            "text": "con",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "sông,",
            "keyword": false
          },
          {
            "text": "một",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "dãy",
            "keyword": false
          },
          {
            "text": "núi.",
            "keyword": false
          }
        ]
      }
    ]
  },
  {
    "id": "vo_19",
    "asset": "images/scene-vo_19.png",
    "motion": "pan-lr",
    "startFrame": 1786,
    "durationFrames": 135,
    "text": "Ranh giới Virginia hay Bắc Carolina uốn lượn theo đúng cách đó,",
    "chunks": [
      {
        "words": [
          {
            "text": "Ranh",
            "keyword": false
          },
          {
            "text": "giới",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "Virginia",
            "keyword": true
          },
          {
            "text": "hay",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "Bắc",
            "keyword": true
          },
          {
            "text": "Carolina",
            "keyword": true
          }
        ]
      },
      {
        "words": [
          {
            "text": "uốn",
            "keyword": false
          },
          {
            "text": "lượn",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "theo",
            "keyword": false
          },
          {
            "text": "đúng",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "cách",
            "keyword": false
          },
          {
            "text": "đó,",
            "keyword": false
          }
        ]
      }
    ]
  },
  {
    "id": "vo_20",
    "asset": "images/scene-vo_20.png",
    "motion": "zoom-in",
    "startFrame": 1921,
    "durationFrames": 80,
    "text": "bám sát địa hình thật ngoài đời.",
    "chunks": [
      {
        "words": [
          {
            "text": "bám",
            "keyword": false
          },
          {
            "text": "sát",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "địa",
            "keyword": false
          },
          {
            "text": "hình",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "thật",
            "keyword": false
          },
          {
            "text": "ngoài",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "đời.",
            "keyword": false
          }
        ]
      }
    ]
  },
  {
    "id": "vo_21",
    "asset": "images/scene-vo_21.png",
    "motion": "static",
    "startFrame": 2001,
    "durationFrames": 104,
    "text": "Vấn đề là những tấm bản đồ thế kỷ mười bảy,",
    "chunks": [
      {
        "words": [
          {
            "text": "Vấn",
            "keyword": false
          },
          {
            "text": "đề",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "là",
            "keyword": false
          },
          {
            "text": "những",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "tấm",
            "keyword": false
          },
          {
            "text": "bản",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "đồ",
            "keyword": false
          },
          {
            "text": "thế",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "kỷ",
            "keyword": false
          },
          {
            "text": "mười",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "bảy,",
            "keyword": false
          }
        ]
      }
    ]
  },
  {
    "id": "vo_22",
    "asset": "images/scene-vo_22.png",
    "motion": "fade-scale",
    "startFrame": 2105,
    "durationFrames": 128,
    "text": "phần lớn dựa trên khảo sát sơ sài của nhà thám hiểm John Smith,",
    "chunks": [
      {
        "words": [
          {
            "text": "phần",
            "keyword": false
          },
          {
            "text": "lớn",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "dựa",
            "keyword": false
          },
          {
            "text": "trên",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "khảo",
            "keyword": false
          },
          {
            "text": "sát",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "sơ",
            "keyword": false
          },
          {
            "text": "sài",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "của",
            "keyword": false
          },
          {
            "text": "nhà",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "thám",
            "keyword": false
          },
          {
            "text": "hiểm",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "John",
            "keyword": true
          },
          {
            "text": "Smith,",
            "keyword": true
          }
        ]
      }
    ]
  },
  {
    "id": "vo_23",
    "asset": "images/scene-vo_23.png",
    "motion": "static",
    "startFrame": 2233,
    "durationFrames": 82,
    "text": "đã sai lệch nhiều so với thực địa.",
    "chunks": [
      {
        "words": [
          {
            "text": "đã",
            "keyword": false
          },
          {
            "text": "sai",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "lệch",
            "keyword": false
          },
          {
            "text": "nhiều",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "so",
            "keyword": false
          },
          {
            "text": "với",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "thực",
            "keyword": false
          },
          {
            "text": "địa.",
            "keyword": false
          }
        ]
      }
    ]
  },
  {
    "id": "vo_24",
    "asset": "images/scene-vo_24.png",
    "motion": "fade-scale",
    "startFrame": 2315,
    "durationFrames": 109,
    "text": "Hệ quả là hàng loạt cuộc tranh chấp biên giới nổ ra.",
    "chunks": [
      {
        "words": [
          {
            "text": "Hệ",
            "keyword": false
          },
          {
            "text": "quả",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "là",
            "keyword": false
          },
          {
            "text": "hàng",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "loạt",
            "keyword": false
          },
          {
            "text": "cuộc",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "tranh",
            "keyword": false
          },
          {
            "text": "chấp",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "biên",
            "keyword": false
          },
          {
            "text": "giới",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "nổ",
            "keyword": false
          },
          {
            "text": "ra.",
            "keyword": false
          }
        ]
      }
    ]
  },
  {
    "id": "vo_25",
    "asset": "images/scene-vo_25.png",
    "motion": "pan-lr",
    "startFrame": 2424,
    "durationFrames": 158,
    "text": "Năm một nghìn tám trăm ba mươi lăm, bang Ohio và vùng lãnh thổ Michigan",
    "chunks": [
      {
        "words": [
          {
            "text": "Năm",
            "keyword": false
          },
          {
            "text": "một",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "nghìn",
            "keyword": false
          },
          {
            "text": "tám",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "trăm",
            "keyword": false
          },
          {
            "text": "ba",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "mươi",
            "keyword": false
          },
          {
            "text": "lăm,",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "bang",
            "keyword": false
          },
          {
            "text": "Ohio",
            "keyword": true
          }
        ]
      },
      {
        "words": [
          {
            "text": "và",
            "keyword": false
          },
          {
            "text": "vùng",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "lãnh",
            "keyword": false
          },
          {
            "text": "thổ",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "Michigan",
            "keyword": true
          }
        ]
      }
    ]
  },
  {
    "id": "vo_26",
    "asset": "images/scene-vo_26.png",
    "motion": "zoom-in",
    "startFrame": 2582,
    "durationFrames": 104,
    "text": "suýt nổ súng vì một sai số khảo sát cũ",
    "chunks": [
      {
        "words": [
          {
            "text": "suýt",
            "keyword": false
          },
          {
            "text": "nổ",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "súng",
            "keyword": false
          },
          {
            "text": "vì",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "một",
            "keyword": false
          },
          {
            "text": "sai",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "số",
            "keyword": false
          },
          {
            "text": "khảo",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "sát",
            "keyword": false
          },
          {
            "text": "cũ",
            "keyword": false
          }
        ]
      }
    ]
  },
  {
    "id": "vo_27",
    "asset": "images/scene-vo_27.png",
    "motion": "static",
    "startFrame": 2686,
    "durationFrames": 122,
    "text": "khiến cả hai cùng tuyên bố chủ quyền dải đất quanh vịnh Maumee,",
    "chunks": [
      {
        "words": [
          {
            "text": "khiến",
            "keyword": false
          },
          {
            "text": "cả",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "hai",
            "keyword": false
          },
          {
            "text": "cùng",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "tuyên",
            "keyword": false
          },
          {
            "text": "bố",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "chủ",
            "keyword": false
          },
          {
            "text": "quyền",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "dải",
            "keyword": false
          },
          {
            "text": "đất",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "quanh",
            "keyword": false
          },
          {
            "text": "vịnh",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "Maumee,",
            "keyword": true
          }
        ]
      }
    ]
  },
  {
    "id": "vo_28",
    "asset": "images/scene-vo_28.png",
    "motion": "fade-scale",
    "startFrame": 2808,
    "durationFrames": 94,
    "text": "sự kiện được gọi là cuộc chiến Toledo.",
    "chunks": [
      {
        "words": [
          {
            "text": "sự",
            "keyword": false
          },
          {
            "text": "kiện",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "được",
            "keyword": false
          },
          {
            "text": "gọi",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "là",
            "keyword": false
          },
          {
            "text": "cuộc",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "chiến",
            "keyword": false
          },
          {
            "text": "Toledo.",
            "keyword": true
          }
        ]
      }
    ]
  },
  {
    "id": "vo_29",
    "asset": "images/scene-vo_29.png",
    "motion": "pan-lr",
    "startFrame": 2902,
    "durationFrames": 135,
    "text": "Vì những rắc rối đó, khi mở rộng về phía tây sau cuộc Cách mạng,",
    "chunks": [
      {
        "words": [
          {
            "text": "Vì",
            "keyword": false
          },
          {
            "text": "những",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "rắc",
            "keyword": false
          },
          {
            "text": "rối",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "đó,",
            "keyword": false
          },
          {
            "text": "khi",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "mở",
            "keyword": false
          },
          {
            "text": "rộng",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "về",
            "keyword": false
          },
          {
            "text": "phía",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "tây",
            "keyword": false
          },
          {
            "text": "sau",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "cuộc",
            "keyword": false
          },
          {
            "text": "Cách",
            "keyword": true
          }
        ]
      },
      {
        "words": [
          {
            "text": "mạng,",
            "keyword": true
          }
        ]
      }
    ]
  },
  {
    "id": "vo_30",
    "asset": "images/scene-vo_30.png",
    "motion": "static",
    "startFrame": 3037,
    "durationFrames": 85,
    "text": "Quốc hội quyết không lặp lại sai lầm.",
    "chunks": [
      {
        "words": [
          {
            "text": "Quốc",
            "keyword": true
          },
          {
            "text": "hội",
            "keyword": true
          }
        ]
      },
      {
        "words": [
          {
            "text": "quyết",
            "keyword": false
          },
          {
            "text": "không",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "lặp",
            "keyword": false
          },
          {
            "text": "lại",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "sai",
            "keyword": false
          },
          {
            "text": "lầm.",
            "keyword": false
          }
        ]
      }
    ]
  },
  {
    "id": "vo_31",
    "asset": "images/scene-vo_31.png",
    "motion": "slide-up",
    "startFrame": 3122,
    "durationFrames": 122,
    "text": "Năm một nghìn bảy trăm tám mươi lăm, họ ban hành đạo luật",
    "chunks": [
      {
        "words": [
          {
            "text": "Năm",
            "keyword": false
          },
          {
            "text": "một",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "nghìn",
            "keyword": false
          },
          {
            "text": "bảy",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "trăm",
            "keyword": false
          },
          {
            "text": "tám",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "mươi",
            "keyword": false
          },
          {
            "text": "lăm,",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "họ",
            "keyword": false
          },
          {
            "text": "ban",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "hành",
            "keyword": false
          },
          {
            "text": "đạo",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "luật",
            "keyword": false
          }
        ]
      }
    ]
  },
  {
    "id": "vo_32",
    "asset": "images/scene-vo_32.png",
    "motion": "static",
    "startFrame": 3244,
    "durationFrames": 86,
    "text": "thiết lập hệ thống khảo sát đất công,",
    "chunks": [
      {
        "words": [
          {
            "text": "thiết",
            "keyword": false
          },
          {
            "text": "lập",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "hệ",
            "keyword": false
          },
          {
            "text": "thống",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "khảo",
            "keyword": false
          },
          {
            "text": "sát",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "đất",
            "keyword": false
          },
          {
            "text": "công,",
            "keyword": false
          }
        ]
      }
    ]
  },
  {
    "id": "vo_33",
    "asset": "images/scene-vo_33.png",
    "motion": "zoom-in",
    "startFrame": 3330,
    "durationFrames": 107,
    "text": "chia lãnh thổ mới thành ô vuông sáu dặm một cạnh,",
    "chunks": [
      {
        "words": [
          {
            "text": "chia",
            "keyword": false
          },
          {
            "text": "lãnh",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "thổ",
            "keyword": false
          },
          {
            "text": "mới",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "thành",
            "keyword": false
          },
          {
            "text": "ô",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "vuông",
            "keyword": false
          },
          {
            "text": "sáu",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "dặm",
            "keyword": false
          },
          {
            "text": "một",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "cạnh,",
            "keyword": false
          }
        ]
      }
    ]
  },
  {
    "id": "vo_34",
    "asset": "images/scene-vo_34.png",
    "motion": "zoom-in",
    "startFrame": 3437,
    "durationFrames": 116,
    "text": "xếp thẳng theo kinh tuyến vĩ tuyến như bàn cờ khổng lồ.",
    "chunks": [
      {
        "words": [
          {
            "text": "xếp",
            "keyword": false
          },
          {
            "text": "thẳng",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "theo",
            "keyword": false
          },
          {
            "text": "kinh",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "tuyến",
            "keyword": false
          },
          {
            "text": "vĩ",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "tuyến",
            "keyword": false
          },
          {
            "text": "như",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "bàn",
            "keyword": false
          },
          {
            "text": "cờ",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "khổng",
            "keyword": false
          },
          {
            "text": "lồ.",
            "keyword": false
          }
        ]
      }
    ]
  },
  {
    "id": "vo_35",
    "asset": "images/scene-vo_35.png",
    "motion": "pan-du",
    "startFrame": 3553,
    "durationFrames": 158,
    "text": "Từ đó, khi Wyoming hay Colorado được thành lập vào cuối thế kỷ mười chín,",
    "chunks": [
      {
        "words": [
          {
            "text": "Từ",
            "keyword": false
          },
          {
            "text": "đó,",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "khi",
            "keyword": false
          },
          {
            "text": "Wyoming",
            "keyword": true
          }
        ]
      },
      {
        "words": [
          {
            "text": "hay",
            "keyword": false
          },
          {
            "text": "Colorado",
            "keyword": true
          }
        ]
      },
      {
        "words": [
          {
            "text": "được",
            "keyword": false
          },
          {
            "text": "thành",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "lập",
            "keyword": false
          },
          {
            "text": "vào",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "cuối",
            "keyword": false
          },
          {
            "text": "thế",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "kỷ",
            "keyword": false
          },
          {
            "text": "mười",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "chín,",
            "keyword": false
          }
        ]
      }
    ]
  },
  {
    "id": "vo_36",
    "asset": "images/scene-vo_36.png",
    "motion": "static",
    "startFrame": 3711,
    "durationFrames": 126,
    "text": "nghị sĩ ở Washington chỉ cần kẻ vài đường thẳng trên giấy,",
    "chunks": [
      {
        "words": [
          {
            "text": "nghị",
            "keyword": false
          },
          {
            "text": "sĩ",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "ở",
            "keyword": false
          },
          {
            "text": "Washington",
            "keyword": true
          }
        ]
      },
      {
        "words": [
          {
            "text": "chỉ",
            "keyword": false
          },
          {
            "text": "cần",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "kẻ",
            "keyword": false
          },
          {
            "text": "vài",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "đường",
            "keyword": false
          },
          {
            "text": "thẳng",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "trên",
            "keyword": false
          },
          {
            "text": "giấy,",
            "keyword": false
          }
        ]
      }
    ]
  },
  {
    "id": "vo_37",
    "asset": "images/scene-vo_37.png",
    "motion": "fade-scale",
    "startFrame": 3837,
    "durationFrames": 124,
    "text": "không cần đặt chân tới vùng đất đó, biên giới vẫn thành hình.",
    "chunks": [
      {
        "words": [
          {
            "text": "không",
            "keyword": false
          },
          {
            "text": "cần",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "đặt",
            "keyword": false
          },
          {
            "text": "chân",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "tới",
            "keyword": false
          },
          {
            "text": "vùng",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "đất",
            "keyword": false
          },
          {
            "text": "đó,",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "biên",
            "keyword": false
          },
          {
            "text": "giới",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "vẫn",
            "keyword": false
          },
          {
            "text": "thành",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "hình.",
            "keyword": false
          }
        ]
      }
    ]
  },
  {
    "id": "vo_38",
    "asset": "images/scene-vo_38.png",
    "motion": "static",
    "startFrame": 3961,
    "durationFrames": 102,
    "text": "Vậy nên đường ranh giới trên bản đồ nước Mỹ",
    "chunks": [
      {
        "words": [
          {
            "text": "Vậy",
            "keyword": false
          },
          {
            "text": "nên",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "đường",
            "keyword": false
          },
          {
            "text": "ranh",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "giới",
            "keyword": false
          },
          {
            "text": "trên",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "bản",
            "keyword": false
          },
          {
            "text": "đồ",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "nước",
            "keyword": false
          },
          {
            "text": "Mỹ",
            "keyword": false
          }
        ]
      }
    ]
  },
  {
    "id": "vo_39",
    "asset": "images/scene-vo_39.png",
    "motion": "fade-scale",
    "startFrame": 4063,
    "durationFrames": 91,
    "text": "không phải một quy luật tự nhiên duy nhất,",
    "chunks": [
      {
        "words": [
          {
            "text": "không",
            "keyword": false
          },
          {
            "text": "phải",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "một",
            "keyword": false
          },
          {
            "text": "quy",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "luật",
            "keyword": false
          },
          {
            "text": "tự",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "nhiên",
            "keyword": false
          },
          {
            "text": "duy",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "nhất,",
            "keyword": false
          }
        ]
      }
    ]
  },
  {
    "id": "vo_40",
    "asset": "images/scene-vo_40.png",
    "motion": "static",
    "startFrame": 4154,
    "durationFrames": 105,
    "text": "mà là dấu vết của hai thời đại khác nhau:",
    "chunks": [
      {
        "words": [
          {
            "text": "mà",
            "keyword": false
          },
          {
            "text": "là",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "dấu",
            "keyword": false
          },
          {
            "text": "vết",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "của",
            "keyword": false
          },
          {
            "text": "hai",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "thời",
            "keyword": false
          },
          {
            "text": "đại",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "khác",
            "keyword": false
          },
          {
            "text": "nhau:",
            "keyword": false
          }
        ]
      }
    ]
  },
  {
    "id": "vo_41",
    "asset": "images/scene-vo_41.png",
    "motion": "pan-lr",
    "startFrame": 4259,
    "durationFrames": 100,
    "text": "một bên là dòng sông và bản đồ sai lệch,",
    "chunks": [
      {
        "words": [
          {
            "text": "một",
            "keyword": false
          },
          {
            "text": "bên",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "là",
            "keyword": false
          },
          {
            "text": "dòng",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "sông",
            "keyword": false
          },
          {
            "text": "và",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "bản",
            "keyword": false
          },
          {
            "text": "đồ",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "sai",
            "keyword": false
          },
          {
            "text": "lệch,",
            "keyword": false
          }
        ]
      }
    ]
  },
  {
    "id": "vo_42",
    "asset": "images/scene-vo_42.png",
    "motion": "pan-lr",
    "startFrame": 4359,
    "durationFrames": 99,
    "text": "một bên là thước kẻ và tọa độ chính xác.",
    "chunks": [
      {
        "words": [
          {
            "text": "một",
            "keyword": false
          },
          {
            "text": "bên",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "là",
            "keyword": false
          },
          {
            "text": "thước",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "kẻ",
            "keyword": false
          },
          {
            "text": "và",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "tọa",
            "keyword": false
          },
          {
            "text": "độ",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "chính",
            "keyword": false
          },
          {
            "text": "xác.",
            "keyword": false
          }
        ]
      }
    ]
  },
  {
    "id": "vo_43",
    "asset": "images/scene-vo_43.png",
    "motion": "zoom-in",
    "startFrame": 4458,
    "durationFrames": 135,
    "text": "Lần tới khi nhìn vào đường biên giới ngoằn ngoèo hay thẳng tắp trên bản đồ,",
    "chunks": [
      {
        "words": [
          {
            "text": "Lần",
            "keyword": false
          },
          {
            "text": "tới",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "khi",
            "keyword": false
          },
          {
            "text": "nhìn",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "vào",
            "keyword": false
          },
          {
            "text": "đường",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "biên",
            "keyword": false
          },
          {
            "text": "giới",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "ngoằn",
            "keyword": false
          },
          {
            "text": "ngoèo",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "hay",
            "keyword": false
          },
          {
            "text": "thẳng",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "tắp",
            "keyword": false
          },
          {
            "text": "trên",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "bản",
            "keyword": false
          },
          {
            "text": "đồ,",
            "keyword": false
          }
        ]
      }
    ]
  },
  {
    "id": "vo_44",
    "asset": "images/scene-vo_44.png",
    "motion": "static",
    "startFrame": 4593,
    "durationFrames": 127,
    "text": "hãy tự hỏi: nó đang kể cho bạn nghe câu chuyện của địa lý,",
    "chunks": [
      {
        "words": [
          {
            "text": "hãy",
            "keyword": false
          },
          {
            "text": "tự",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "hỏi:",
            "keyword": false
          },
          {
            "text": "nó",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "đang",
            "keyword": false
          },
          {
            "text": "kể",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "cho",
            "keyword": false
          },
          {
            "text": "bạn",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "nghe",
            "keyword": false
          },
          {
            "text": "câu",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "chuyện",
            "keyword": false
          },
          {
            "text": "của",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "địa",
            "keyword": false
          },
          {
            "text": "lý,",
            "keyword": false
          }
        ]
      }
    ]
  },
  {
    "id": "vo_45",
    "asset": "images/scene-vo_45.png",
    "motion": "fade-scale",
    "startFrame": 4720,
    "durationFrames": 70,
    "text": "hay câu chuyện của quyền lực?",
    "chunks": [
      {
        "words": [
          {
            "text": "hay",
            "keyword": false
          },
          {
            "text": "câu",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "chuyện",
            "keyword": false
          },
          {
            "text": "của",
            "keyword": false
          }
        ]
      },
      {
        "words": [
          {
            "text": "quyền",
            "keyword": false
          },
          {
            "text": "lực?",
            "keyword": false
          }
        ]
      }
    ]
  }
];
